server:
  port: 9000
logging:
  level:
    root: INFO
    '[org.springframework.web]': ERROR
    # '[org.springframework.security]': DEBUG
    # '[org.springframework.security.oauth2]': DEBUG
spring:
  security:
    oauth2:
      client:
        registration:
          google-idp:
            provider: google
            client-id: ${GOOGLE_CLIENT_ID:970880456680-nn0tu84c95v7ph2dfp0csrrk7i12h926.apps.googleusercontent.com}
            client-secret: ${GOOGLE_CLIENT_SECRET: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}
            scope: openid, https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/userinfo.email
            client-name: Sign in with Google
          github-idp:
            provider: github
            client-id: ${GITHUB_CLIENT_ID:github-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:github-client-secret}
            scope: user:email, read:user
            client-name: Sign in with GitHub
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            # user-info-uri: ${okta.base-url}/oauth2/v1/userinfo
            # jwk-set-uri: ${okta.base-url}/oauth2/v1/keys
            user-name-attribute: email
          github:
            user-name-attribute: login
# Propiedades personalizadas
jwt:
  private.key: classpath:rsa/app.key
  public.key: classpath:rsa/app.pub
