server:
  port: 9000
logging:
  level:
    root: INFO
    '[org.springframework.web]': TRACE
    '[org.springframework.security]': DEBUG
    '[org.springframework.security.oauth2]': DEBUG
# Propiedades personalizadas
jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub