server:
  port: 8091
logging:
  level:
    root: INFO
    '[org.springframework.web]': TRACE
    '[org.springframework.security]': DEBUG
    '[org.springframework.security.oauth2]': DEBUG
spring:
  application:
    name: fact
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9000
      client:
        registration:
          fact-client-oidc:
            provider: spring
            client-id: fact-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8091/authorized
            scope: read
            client-name: fact-client-oidc
        provider:
          spring:
            issuer-uri: http://127.0.0.1:9000
