logging:
  level:
    root: INFO
    '[org.springframework.web]': TRACE
    '[org.springframework.security]': DEBUG
    '[org.springframework.security.oauth2]': DEBUG
spring:
  security:
    oauth2:
      resourceserver:
          jwt:
            issuer-uri: http://127.0.0.1:9000
      client:
        registration:
          pagos-client-oidc:
            provider: spring
            client-id: pagos-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8090/authorized
            scope: read
            client-name: pagos-client-oidc
        provider:
          spring:
            issuer-uri: http://127.0.0.1:9000
